In [1]:
### 1️⃣ 진법형 → 정수형  

# 진법 접두어가 포함된 데이터
data = ['0b1101', '0x1A', '0o17']  # 2진수, 16진수, 8진수

# 전처리: 10진수로 변환
processed = [int(x, 0) for x in data]

print(processed)  # [13, 26, 15]


[13, 26, 15]


In [2]:
### 2️⃣ 문장형 → 벡터형 (문장 임베딩 using SentenceTransformer)

from sentence_transformers import SentenceTransformer

# 문장 데이터
sentences = ["설비 고장 발생", "모터 과열 경고", "정상작동 완료"]

# 모델 로딩 (사전 훈련된 모델)
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

# 문장 임베딩
embeddings = model.encode(sentences)

print(embeddings[0])  # 예: [0.12, -0.04, ..., 0.17] 형태의 벡터



d:\task_folder\sources\IND_prep\test_venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


[-0.06866315  0.48343346  0.08009468 -0.16355862  0.06944454  0.31017786
  1.2657273   0.00862303  0.32404584 -0.15729403  0.4191875  -1.3553168
 -0.12609965  0.13410422 -0.06823592 -0.16136016 -0.06993854  0.06264389
 -0.6248212  -0.06965591  0.30633906  0.10673854  0.13752078 -0.30339357
 -0.25134686 -0.23577659  0.33265707  0.17095321 -0.5030148   0.0725638
  0.30380833 -0.22755215  0.12381352 -0.00406363  0.3664697   0.5397188
 -0.4816956   0.22376397  0.13030283 -0.37940645  0.13352102 -0.3389914
  0.3989193   0.47351348  0.14908245  0.46871006 -0.05419172 -0.21702057
  0.10205945  0.06605849 -0.7494495  -0.4235811   0.57400054 -0.12158324
  0.48264217 -0.6624782   0.2259987   0.6295669   0.06055915  0.3205856
 -0.6206253   0.53462267 -1.3497666   0.5438862  -0.11321126  0.02875172
 -0.34074107  0.29572237  0.09097854 -0.4318726   0.32821974  0.3284505
 -0.3175068   0.24806292 -0.6266717  -0.40567958  0.34302375 -0.03074554
  0.02309131  0.47087193 -0.2906774  -0.63876086 -0.09258

In [19]:



### 3️벡터형(다차원) → 소수형 (Flatten 후 PCA)

from sklearn.decomposition import PCA
import numpy as np

# 다차원 벡터 (샘플 2개, 각 샘플은 4×3 벡터)
data = np.array([
    [[1.2, 3.4, 5.6], [2.1, 0.3, 7.8], [1.2, 0.5, 6.2], [1.0, 2.1, 3.8]],
    [[0.5, 1.0, 1.5], [0.9, 0.2, 2.5], [0.3, 0.1, 2.8], [0.2, 1.1, 3.3]]
])  # shape: (2, 4, 3)

# Flatten: (2, 12)
flattened = data.reshape(data.shape[0], -1)

# PCA로 차원 축소
pca = PCA(n_components=2)
reduced = pca.fit_transform(flattened)

print(reduced)  # shape: (2, 3), 결과는 소수형




[[ 4.09328719e+00  8.17406414e-16]
 [-4.09328719e+00  8.17406414e-16]]


In [21]:
data = np.random.rand(5, 4, 3)  # 샘플 5개
flattened = data.reshape(data.shape[0], -1)



In [23]:
flattened

array([[0.52453722, 0.43851251, 0.33047426, 0.75826898, 0.19555526,
        0.19104104, 0.20243359, 0.81972282, 0.08785459, 0.79672009,
        0.79556165, 0.41565958],
       [0.48325795, 0.09056458, 0.62664854, 0.37562401, 0.9961627 ,
        0.95729499, 0.72318609, 0.07927442, 0.83667553, 0.10972607,
        0.70146934, 0.13775755],
       [0.29887299, 0.50112881, 0.2101722 , 0.9920723 , 0.28367777,
        0.60323057, 0.05143253, 0.33089343, 0.96135134, 0.56574458,
        0.1011498 , 0.83776801],
       [0.95917342, 0.20574539, 0.78202613, 0.42804882, 0.90311768,
        0.18606325, 0.50721946, 0.68013163, 0.1181926 , 0.36048525,
        0.45344237, 0.56734261],
       [0.84029597, 0.5477787 , 0.53829466, 0.64057091, 0.01138392,
        0.87801229, 0.73736627, 0.78981671, 0.62181667, 0.29361863,
        0.09577219, 0.63794869]])

In [24]:
pca = PCA(n_components=3)
reduced = pca.fit_transform(flattened)
print(reduced)  # shape: (5, 3)

[[-0.56516509 -0.60095602 -0.31470256]
 [ 1.05636876  0.32844992 -0.22166191]
 [-0.56485357  0.69819284 -0.33434531]
 [ 0.31116785 -0.71686767  0.13532496]
 [-0.23751796  0.29118093  0.73538482]]
